apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: echo-spring
  namespace: echo-web
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-spring
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: echo-spring-backend
  namespace: echo-backend
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-spring-backend
  targetCPUUtilizationPercentage: 70