apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-spring-ingress
  namespace: web
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  ingressClassName: contour
  rules: []
  tls:
status:
  loadBalancer: {}
