apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: echo-spring
  namespace: web
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-spring
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: echo-spring-backend
  namespace: backend
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-spring-backend
  targetCPUUtilizationPercentage: 50