apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-spring
spec:
  containers:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-spring-backend
  namespace: backend
spec:
  containers:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"