- op: add
  path: /spec/rules/-
  value:
    host: echo.dev-cluster.h2o-2-1565.h2o.vmware.com
    http:
      paths:
      - backend:
          service:
            name: echo-spring
            port:
              number: 443
        path: /echo-spring
        pathType: Prefix

- op: add
  path: /spec/tls
  value:
    - hosts:
      - "echo.dev-cluster.h2o-2-1565.h2o.vmware.com"
      secretName: dev-cluster-ca-cert
  